apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-letsencrypt-tls

  dnsNames:
    - "argocd.brentdb.nl"

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
