apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: argocd-letsencrypt-tls

  dnsNames:
    - "argocd.brentdb.nl"

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
