name: Terraform Destroy - Main Cluster

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm destruction'
        required: true
        type: string

jobs:
  terraform-destroy:
    uses: ./.github/workflows/terraform-template.yml
    with:
      cluster: main
      action: destroy
      confirm_destroy: ${{ github.event.inputs.confirm_destroy }}
    secrets: inherit
